batch_size: 32
height: 50
learning_rate: 0.001
max_text_length: 9
model_path: Models/02_captcha_to_text/202311191731
train_epochs: 1000
train_workers: 20
vocab: 5P1HgLZWI2Me9QBFK0aN7iOCD_Y648mEAXV3SGJTR
width: 130
